name: social-branding

up:
  - ruby: 2.3.1
  - bundler

commands:
  test: bundle exec rake test
  rake:
    syntax:
      optional: args...
    desc: 'bin/rake ...'
    run: bin/rake
  rspec:
    syntax:
      optional: args...
    desc: 'bin/bundle exec rspec'
    run: bin/bundle exec rspec
  be:
    syntax:
      optional: args...
    desc: 'bin/bundle exec ...'
    run: bin/bundle exec

packages:
  - git@github.com:Shopify/dev-shopify.git
